apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api-ingress-green
  namespace: deployment-strategy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "simple-api-green.192.168.0.58.sslip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: simple-api-preview
            port:
              number: 8080
