apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- simple-api-svc.yaml
- simple-api-deployment.yaml
- simple-api-gateway.yaml

images:
- name: skaqud/simple-api
  newTag: RB0.0.7
