apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- simple-api-deployment.yaml
- simple-api-svc.yaml
- simple-api-ingress.yaml

images:
- name: oscka/simple-api
  newTag: 0.0.1