apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: sample    
  
  labels:
    app: simple-api
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      
      labels:
        app: simple-api     
    spec:
      containers:
        - name: simple-api
          image: oscka/simple-api   #docker 이미지 주소
          ports:
          - name: http
            containerPort: 8080
