apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api-ingress
  namespace: sample
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "simple-api.127.0.0.1.sslip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: simple-api-svc
            port:
              number: 8080